training_arguments:
  output_dir: function-calling

  num_train_epochs: 0.05
  learning_rate: 2.0e-4
  warmup_ratio: 0.05
  weight_decay: 0.01

  # auto_find_batch_size: True
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  # gradient_checkpointing: True
  group_by_length: True

  evaluation_strategy: steps
  eval_steps: 10
  save_strategy: steps
  save_steps: 10
  load_best_model_at_end: True
  # include_inputs_for_metrics: True
  report_to: none

  fp16: True
  optim: paged_adamw_8bit

model:
  name: TheBloke/Mistral-7B-Instruct-v0.2-GPTQ
  device: auto
  tokenizer_args:
    use_fast: True
  lora_args:
    r: 8
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj"]
    lora_dropout: 0.05
    bias: "none"
    task_type: "CAUSAL_LM"

data:
  name: korotkov/glaive-function-calling-v2-parsed
  format: llama
  tokenizer_args:
    return_tensors: np
    truncation: True
    max_length: 512
