training_args:
  run_name: llama-7b-1
  output_dir: results/llama-7b-1

  num_train_epochs: 1.0
  learning_rate: 2.0e-4
  warmup_ratio: 0.05
  weight_decay: 0.01

  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 2
  gradient_checkpointing: False
  # group_by_length: True

  eval_delay: 0
  evaluation_strategy: steps
  eval_steps: 100
  save_strategy: steps
  save_steps: 100
  load_best_model_at_end: True
  include_num_input_tokens_seen: True
  report_to: wandb

  fp16: True
  optim: paged_adamw_8bit

sft_trainer_args:
  packing: True
  max_seq_length: 2048

model:
  name: meta-llama/Llama-2-7b-chat-hf
  device: cuda
  tokenizer_args:
    use_fast: True
  lora_args:
    r: 8
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj"]
    lora_dropout: 0.05
    bias: "none"
    task_type: "CAUSAL_LM"

data:
  name: korotkov/glaive-function-calling-v2-parsed
  format: llama
  loss_eval_samples: 1000
  metrics_eval_samples: 100

metrics_callback:
  max_new_tokens: 128

filter_warnings: True
